Only allow one dataset to have a name
Team846/funky-dashboard pull request #28
Opened 2018-01-14 00:31 UTC by akainth015

Check if any datasets already have the same name as the one being added. If there is already a dataset with the same name, an IllegalArgumentException will be thrown.

2018-01-14 04:44 UTC, kunalsheth reviewed
lgtm

2018-01-14 19:10 UTC, shadaj requested changes
One change needed to the exception, but otherwise it's good.

2018-01-14 19:10 UTC, shadaj commented on jvm/src/main/scala/com/lynbrookrobotics/funkydashboard/DatasetGroup.scala
> +      throw new IllegalArgumentException(s"Overriding name of existing DatasetGroup(${this.properties.name})")
Hmm, but you're not actually doing that? You're just throwing an exception, preventing the dataset group from being overriden.

2018-01-20 20:31 UTC, shadaj commented on jvm/src/main/scala/com/lynbrookrobotics/funkydashboard/DatasetGroup.scala
> +    if (datasets.map(_.definition.name).contains(dataset.definition.name)) {
Can be replaced with a single `exists`, or better yet `find` so you get access to dName.

2026-05-01 18:26 UTC, closed without merging